// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KVSC.Data.Models;

public partial class DoctorsSchedule
{
    public int ScheduleId { get; set; }

    public int? DoctorId { get; set; }

    public DateOnly? AvailableDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string TimeSlot { get; set; }

    public bool? IsAvailable { get; set; }

    public string SpecialDays { get; set; }

    public int? MaxAppointments { get; set; }

    public string Notes { get; set; }

    public virtual Doctor Doctor { get; set; }
}