// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KVSC.Data.Models;

public partial class Fish
{
    public int FishId { get; set; }

    public int? CustomerId { get; set; }

    public int? PondId { get; set; }

    public string Name { get; set; }

    public string Breed { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string HealthStatus { get; set; }

    public DateOnly? LastCheckupDate { get; set; }

    public string Notes { get; set; }

    public string Color { get; set; }

    public decimal? Size { get; set; }

    public string Photo { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Customer Customer { get; set; }

    public virtual Pond Pond { get; set; }
}