// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KVSC.Data.Models;

public partial class Pond
{
    public int PondId { get; set; }

    public string PondSize { get; set; }

    public string WaterQuality { get; set; }

    public DateOnly? LastMaintenanceDate { get; set; }

    public int? Capacity { get; set; }

    public string Notes { get; set; }

    public string Location { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? LastUpdate { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Fish> Fish { get; set; } = new List<Fish>();
}