// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KVSC.Data.Models;

public partial class ServiceCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? IsActive { get; set; }

    public int? ParentCategoryId { get; set; }

    public int? DisplayOrder { get; set; }

    public string Notes { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();
}