// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KVSC.Data.Models;

public partial class ServiceRequest
{
    public int RequestId { get; set; }

    public int? CustomerId { get; set; }

    public int? ServiceId { get; set; }

    public DateTime? RequestDate { get; set; }

    public string RequestDetails { get; set; }

    public string Status { get; set; }

    public int? AssignedDoctorId { get; set; }

    public DateTime? CompletionDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Feedback { get; set; }

    public string Notes { get; set; }

    public virtual Doctor AssignedDoctor { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Service Service { get; set; }
}